### ISSUE TITLE
Missing @types/node

### ISSUE THREAD

**Issue by eric-burel** [capri-js/capri#33]
After running `yarn create capri my-app -e react`, `vite.config.ts` will use `process` yet `@types/node` is not installed, making TypeScript unhappy. It should be added as dev dependency to the package.json to fix this issue.

I couldn't figure how to send a PR for that though because I didn't find where the template projects are defined?

**Comment by fgnass** [comment]
Oh yes, thanks for reporting it! I went a different route and removed the base setting (and process.env) from vite.config.ts altogether, as it was only used for the GitHub pages deployment of the examples. BTW, the code for the examples that is used by create-capri lives in https://github.com/capri-js/capri/tree/next/examples
