### ISSUE TITLE
Typo in data fetching example

### ISSUE THREAD

**Issue by jablonski** [capri-js/capri#37]
There's a small typo in the data fetching example which is hard to detect and which prevents data loading for static builds:

https://capri.build/docs/frameworks/react/

`const user = useSWR("https://api.example.com", fetcher, { suspsense: true });`

Should be:

`const user = useSWR("https://api.example.com", fetcher, { suspense: true });`

It needs to be **suspense** instead of _suspsense_.

**Comment by fgnass** [comment]
Thank you! I fixed it.
