### ISSUE TITLE
React helmet

### ISSUE THREAD

**Issue by vincent-vade** [capri-js/capri#45]
Hi,

I like capri and it useful library...

I'm actually working on head seo tag and i've try to add react helmet but not successfully.
Do you have any example or suggestion how to implement it ?

regards 

Vincent

**Comment by fgnass** [comment]
Sure, here is a quick example: https://stackblitz.com/edit/capri-helmet?file=src%2Fmain.server.tsx

The only thing that is currently not supported is using `helmet.htmlAttributes` and `helmet.bodyAttributes `.

**Comment by vincent-vade** [comment]
@fgnass Perfect thank for the example
